### PR TITLE
Fix serial bug

### PR DESCRIPTION
**Pull request by rec**
The time-consuming part was writing the unit test but finally I understand unittest.mock anyway.

### CODE REVIEW

**Comment by adammhaile** [comment]
@rec 
$ flake8
./test/bibliopixel/drivers/serial/driver_test.py:46:13: E123 closing bracket does not match indentation of opening bracket's line

**Comment by rec** [comment]
Fixed!

**Comment by adammhaile** [comment]
ack, will pull and test later tonight.

**Comment by rec** [comment]
So I think you established last night that this is an improvement, so we should merge this and I can continue?

**Comment by adammhaile** [comment]
Yeah, needs more testing, but looks good enough to move forward.

**Pull request merged**
