### PR TITLE
Remove or mark with noqa all instances of `print`

### PR DESCRIPTION
**Pull request by rec**
* Eliminate all style violations found by `flake8-print`
* Now we can use `print` for debugging and have it caught by our flake8

### CODE REVIEW

**Comment by rec** [comment]
It also means that we can later easily redirect all output by redirecting `log.printer`.

**Comment by rec** [comment]
Good idea!

**Comment by rec** [comment]
Let me see if that works with Travis, and then I'll push it.

**Comment by adammhaile** [comment]
Cool

**Pull request merged**
