### PR TITLE
Fix `bp demo`

### PR DESCRIPTION
**Pull request by rec**
There's a weirdness with the circle demo that does something more interesting than is actually programmed in :-o but it'll work fine as a demo.

### CODE REVIEW

**Comment by adammhaile** [comment]
Wait... circle wasn't causing the issue though, right? What's wrong with Circle?

**Comment by rec** [comment]
All five demos failed, at least when I tried them!  One was a dupe...

**Comment by adammhaile** [comment]
I know all five failed. That's why I was asking what was specific about circle.

**Comment by rec** [comment]
Well, I changed circle to be a project, because then I could get rid of that whole codepath where demos weren't projects...

I'm not exactly sure what it was doing before, to be honest.

**Comment by adammhaile** [comment]
lol
+1

**Pull request merged**
