### PR TITLE
Order URL parameters (perhaps fix #885)

### LINKED ISSUE #885: REST multi controls don't work if changing animation index and current animation properties at same time
REST multi controls work great if you are changing multiple properties on the current running animation.

However if you do something like `?animation.index=4&animation.animation.brightness=10` it doesn't pass that brightness value to the animation you are setting it too (but probably the last one).

Note, I don't know that there is any way around this, as the multi-control probably runs immediately and the animation doesn't switch immediately.

Perhaps what is needed instead is some kind of control that can say switch to this animation and pass in these values after you switch to it.

You can of course do slightly hacky things like switch to an animation, sleep for 10ms, then send your parameters you want for that animation. However, obviously hard to time exactly, can end up not passing them in because not running yet or passing them in and getting some kind of flicker.

### PR DESCRIPTION
**Pull request by rec**
Might or might not fix #885 but at least we are guaranteed that the order of the URL data keys is preserved!

(flask doesn't do it this way by default for "efficiency", which is bogus if you ask me.)

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by estiens** [comment]
Get a stacktrace after I merge this one in and bp won't start
```
  File "/anaconda3/envs/bibliopixel/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/bibliopixel/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/util/threads/animation_threading.py", line 35, in target
    self.run()
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/animation.py", line 108, in run_all_frames
    for i in self.generate_frames():
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/animation.py", line 112, in generate_frames
    with self._run_context(clean_layout):
  File "/anaconda3/envs/bibliopixel/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/animation.py", line 171, in _run_context
    self.pre_run()
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/sequence.py", line 28, in pre_run
    super().pre_run()
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/indexed.py", line 47, in pre_run
    self.index = 0
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/indexed.py", line 32, in index
    self._on_index(old_index)
  File "/anaconda3/envs/bibliopixel/lib/python3.6/site-packages/bibliopixel/animation/sequence.py", line 48, in _on_index
    step = self.offset + self.index
AttributeError: 'Sequence' object has no attribute 'offset'
```

**Comment by estiens** [comment]
(nb, not nec from this commit, but from a dev commit that happened within past couple days since last time I pulled it down)

**Comment by estiens** [comment]
If I revert to 2da282671ca8c1977d8f05bb81da1cc6f943a558 bp still starts up, so issue is somewhere in between

**Comment by rec** [comment]
(That has been pushed...)

**Pull request merged**
