### PR TITLE
Fix integer issues in color math.

### PR DESCRIPTION
**Pull request by rec**
Took me too long to realize that the crash was in HEAD and not my code!

(Not sure how "demo" works for you...??)

### CODE REVIEW

**Comment by adammhaile** [comment]
The demo doesn't scale the colors as it's always at full brightness. Which in my testing last night worked fine.
What do you mean not in your code?
+1 btw

**Comment by rec** [comment]
Oops, not so clear on my part!  I meant I was preparing to make some other unrelated change and thought I'd caused this issue and it took me a bit to figure out that I wasn't.

I don't see how the demo could ever have worked though.  It's trying to index arrays with a non-integer!

**Comment by rec** [comment]
Here's the command I executed that failed on dev/HEAD:

`PYTHONPATH=/development/BiblioPixelAnimations python /development/BiblioPixel/main.py demo`

**Comment by adammhaile** [comment]
Not sure.   Automatic cast attempt? Well it's hardened against that now...

**Comment by rec** [comment]
I'm on the brightness stuff then!

**Pull request merged**
