### PR TITLE
Compute animation.name in Animation.pre_recursion (fix #722 and #723)

### LINKED ISSUE #722: `bp -v ../BiblioPixelAnimations/Projects/circle.json` fails
bp -v ../BiblioPixelAnimations/Projects/circle.json 
WARNING - deprecated - Circle.lastRing
ERROR - failed - Unable to create animation for {'bgcolor': 'black', 'port': 5000, 'title': 'circle Demo', 'external_access': True, 'name_map': {'Swirl': 9, 'ArcRotate': 1, 'PinWheel': 8, 'FireFlies': 5, 'CircleClock': 3, 'ArcClock': 0, 'HyperspaceRainbow': 7, 'OFF_ANIM': 10, 'Diag': 4, 'CircleBloom': 2, 'Hyperspace': 6}, 'animations': [<BiblioPixelAnimations.circle.arc_clock.ArcClock object at 0x106e4c4e0>, <BiblioPixelAnimations.circle.arc_rotate.ArcRotate object at 0x106e4c5c0>, <BiblioPixelAnimations.circle.bloom.CircleBloom object at 0x106e4c6d8>, <BiblioPixelAnimations.circle.circle_clock.CircleClock object at 0x106e4c7f0>, <BiblioPixelAnimations.circle.diag.Diag object at 0x106e4c908>, <BiblioPixelAnimations.circle.fireflies.FireFlies object at 0x106e4ca20>, <BiblioPixelAnimations.circle.hyperspace.Hyperspace object at 0x106e4cb38>, <BiblioPixelAnimations.circle.hyperspace.HyperspaceRainbow object at 0x106b44240>, <BiblioPixelAnimations.circle.pinwheel.PinWheel object at 0x106b44e10>, <BiblioPixelAnimations.circle.swirl.Swirl object at 0x106b44ef0>, <bibliopixel.animation.off.Off object at 0x106b44400>], 'default': None}
ERROR - failed - 
Traceback (most recent call last):
  File "/development/BiblioPixel/bibliopixel/animation/animation.py", line 20, in construct
    a = cls(project.layout, **desc)
  File "/development/BiblioPixel/bibliopixel/animation/remote/control.py", line 114, in __init__
    self.index = self.name_map[DEFAULT_OFF]  # start with default animation
  File "/development/BiblioPixel/bibliopixel/animation/wrapper.py", line 30, in index
    index = self.animations._index(index)
AttributeError: 'list' object has no attribute '_index'

### PR DESCRIPTION
**Pull request by rec**

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by adammhaile** [comment]
+1 - sorry, hit wrong button.

**Comment by adammhaile** [comment]
oops... checks failed

**Comment by rec** [comment]
_Alles goed._

**Pull request merged**
