### PR TITLE
fixup! Add a unit test for sequences and fix some issues.

### PR DESCRIPTION
**Pull request by rec**
Oh, how embarrassing.  

With your permission, I'm going to actually fold this into dev/HEAD so it will be as if this mistake never happened - not to obscure blame, but rather to not have a bad commit ID in the list (even if we aren't currently testing for that problem).

### CODE REVIEW

**Comment by rec** [comment]
Urg, on the travis breakage, moment pls.

**Comment by rec** [comment]
Fixed.

**Comment by rec** [comment]
So shall I rebase this over dev, then??

If not, I'll give the commit a better name.

**Comment by adammhaile** [comment]
I'd rather it just PR in like normal... Then I don't have to force pull or
anything.

**Comment by rec** [comment]
Wilco!  I have a guest here, this won't happen for a bit...

**Comment by adammhaile** [comment]
I need to get on with remote updates. Can I just merge these all then?

**Comment by adammhaile** [comment]
Actually... only the remote json file one really matters for me. Carry on.

**Pull request merged**
