### PR TITLE
Allow strings as colors in `layout.set` (fix #508)

### LINKED ISSUE #508: Allow strings as colors in `layout.set`
We should allow `layout.set` and the various methods on derived classes to take a string as a pixel value, which we automatically convert to an RGB value (or throw an exception).

### PR DESCRIPTION
**Pull request by rec**
There's no unit test that covers this.  Suggestions?

### CODE REVIEW

**Comment by adammhaile** [comment]
lgtm

**Comment by rec** [comment]
(I haven't forgotten this - I just need to figure out a unit test...)

**Comment by rec** [comment]
All right, I wrote a unit test - ready to go.

**Comment by adammhaile** [comment]
+1

**Pull request merged**
