### PR TITLE
`bp` can now save and load defaults locally

### PR DESCRIPTION
**Pull request by rec**
* Fully backwards compatible, but you can now specify full paths
  in loading and saving.

* Turns out that you want to save your defaults with your project and use
  them that way.

* Motivating example: you want to just check out your project on a new machine
  and type:

    bp project/1.json project/2.json --defaults=my-defaults.json

### CODE REVIEW

**Comment by rec** [comment]
All right, I pushed another change - the final one here I hope - that allows multiple default files.

In my project, I say either:

    bp -vs projects/04-bitsstream.json -d base.json -d simpixel.json 
    bp -vs projects/04-bitsstream.json -d base.json -d strip.json 

* [base.json](https://github.com/rec/christmas_lights/blob/master/base.json)
* [simpixel.json](https://github.com/rec/christmas_lights/blob/master/simpixel.json)
* [strip.json](https://github.com/rec/christmas_lights/blob/master/strip.json)

Isn't that neat?  :-)

**Comment by adammhaile** [comment]
Sweet :) +1

**Comment by rec** [comment]
My workflow is really coming along.  I have a ton of cool new strip animations too, most of which demonstrate how to use numpy arrays.

**Comment by adammhaile** [comment]
Awesome! Can't wait to see them!

**Pull request merged**
