### PR TITLE
New --external flag.

### PR DESCRIPTION
**Pull request by rec**

### CODE REVIEW

**Comment by rec** [comment]
I don't like `--external` but `--sanity-check` doesn't seem really super.

What are we doing...?  We're checking to see - if we can share this code.

`--check_shareable`

Urg, I just realized that I need to add something else... moment pls!

**Comment by rec** [comment]
I am now also checking the path passed to gitty.

Got a better name?

    --check_shareable
    --check_push

???

**Comment by adammhaile** [comment]
Check dist?

**Comment by rec** [comment]
My final thought on this is that we won't come up with a final name until we have names for the whole upload/sharing procedure, so I'm going to squash and push, and then we'll change the name when we've unified our nomenclature.

**Comment by rec** [comment]
Fixes #329.

**Pull request merged**
