### PR TITLE
Delete commands from `bp` with feature flag `BP_DELETED_COMMANDS`

### PR DESCRIPTION
**Pull request by rec**

### CODE REVIEW

**Comment by adammhaile** [comment]
I'm confused as to what's going on here.

**Comment by rec** [comment]
There are two groups of commands that we should probably delete.

`bp update` doesn't work as well as `pip3 install -U bibliopixel` does.

The user default commands change these hidden preferences files in your home directory and are dangerous, and offer nothing over `bp defaults.yml+project.yml`.

But I might be wrong.  So I didn't delete those commands - I just disabled them with a feature flag, one that we could turn on again if we liked.

**Comment by rec** [comment]
Ping!

**Comment by adammhaile** [comment]
+1

**Comment by rec** [comment]
My theory is that no one will want these commands back.  If they do, we can tell 'em to set that environment variable temporarily... :-)

**Pull request merged**
