### PR TITLE
Stop projects from looping (probably fix #1085)

### LINKED ISSUE #1085: Projects stop, disconnect from AllPixel, and restart
@rec - WTF is up with this? Scroll near the bottom and you'll see `stop called on pid 1252`, it disconnects from serial, and completely restarts. This shouldn't happen.

```
G:\dev\BiblioPixel>bp --loglevel=frame run --ledtype WS2812 G:\dev\BiblioPixel\scripts\release_test\projects\all_pixel.yml
WARNING - load - This "path" entry does not exist: "G"
INFO - devices - Using COM Port: COM7, Device ID: 42, Device Ver: 0
DEBUG - project_runner - Running file G:\dev\BiblioPixel\scripts\release_test\projects\all_pixel.yml
DEBUG - animation_threading - Animation starts on main thread
WARNING - animation - 14ms/67fps / Frame: 0ms / Update: 14ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/980fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/938fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/985fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/955fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/999fps / Frame: 0ms / Update: 1ms
WARNING - animation - 1ms/849fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/979fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/864fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/830fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 1ms/919fps / Frame: 0ms / Update: 1ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
DEBUG - animation_threading - Animation complete
DEBUG - project - Project <bibliopixel.project.project.Project object at 0x107EA4F0>
stop called on pid 1252
INFO - driver - Closing connection to: COM7
DEBUG - project - Project <bibliopixel.project.project.Project object at 0x107EA4F0>
finishes run()
WARNING - load - This "path" entry does not exist: "G"
INFO - devices - Using COM Port: COM7, Device ID: 42, Device Ver: 0
DEBUG - project_runner - Running file G:\dev\BiblioPixel\scripts\release_test\projects\all_pixel.yml
DEBUG - animation_threading - Animation starts on main thread
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
WARNING - animation - 0ms/1000fps / Frame: 0ms / Update: 0ms
```

### PR DESCRIPTION
**Pull request by rec**
This happened when I was abstracting the signal handling to make the Project Builder work.

The breakage is unfortunate, but I think the Project Builder is worth the inconvenience...

### CODE REVIEW

**Comment by adammhaile** [comment]
I'm confused, are you saying that projects will now only run once and never loop? That would be unacceptable. How would you have an endlessly running animation? It should always keep running until the end of time unless explicitly told otherwise.

**Comment by rec** [comment]
No, I just introduced a breakage that made _everything_ run forever.

This fixed that breakage only.

Look at the actual code that was fixed.  It has zero to do with projects specifically - what it does is runs something and wait for signals.

Now, if we come back from running that something, and there are no signals, that means we are done. 

Only in one case are we not done - when we are interrupted because we got a signal AND that signal was a HUP.

This outside the whole project world.  The project runs to completion, or not, just as before.

**Comment by adammhaile** [comment]
Alright, just confirming.

**Comment by rec** [comment]
I cleaned up the description above a little. 

Also, it certainly deserves explanation as to how it works.  

On the API end, this is lovely and clear: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/commands/run.py#L10-L12

This handles SIGHUP, SIGINT, SIGTERM and normal termination, and it is completely invisible to the project runner.  All it needs to prove is some `stop` method or function!

**Pull request merged**
